import DOMPurify from "dompurify";
import Tooltip from "./Tooltip";

// Tag text is trusted markup generated by the AVideo backend (e.g. status icons
// like '<i class="fas fa-lock"></i>'), not raw user input - still sanitized as defense in depth.
export default function TagList({ tags }) {
    return (
        <div className="flex flex-wrap gap-1 mt-2">
            {tags
                .filter(tag => tag.text && tag.text !== "0")
                .map((tag, index) => (
                    <Tooltip key={index} content={tag.tooltip || tag.label}>
                        <span
                            className="text-xs bg-gray-100 dark:bg-gray-700 text-gray-800 dark:text-gray-200 px-2.5 py-1 rounded-full truncate max-w-[8rem]"
                            dangerouslySetInnerHTML={{ __html: DOMPurify.sanitize(`#${tag.text}`) }}
                        />
                    </Tooltip>
                ))}
        </div>
    );
}
